version: '3'

volumes:
    django_static:

services:
    nginx:
        container_name: nginx
        build: ./nginx
        environment:
            - TZ=Asia/Seoul
        image: docker-server/nginx
        restart: always
        volumes:
            - /var/www/certbot:/var/www/certbot
            - /etc/letsencrypt:/etc/letsencrypt
            - /var/lib/letsencrypt:/var/lib/letsencrypt
            - ./nginx/logs:/var/log/nginx
            - django_static:/roccia_901/static
        ports:
            - "8080:80"
            - "8443:443"
        depends_on:
            - backend

    backend:
        container_name: backend
        build: ./backend
        image: docker-server/backend
        env_file:
            - ./backend/.env.prod
        environment:
            - TZ=Asia/Seoul
        restart: always
        command: sh -c "./init.sh"
        volumes:
            - ./backend/logs:/roccia_901/logs
            - django_static:/roccia_901/static
        expose:
            - 8000
        depends_on:
            - cache

    cache:
        container_name: cache
        image: redis:7
        command: redis-server /etc/redis/redis.conf
        volumes:
            - ./redis/redis.conf:/etc/redis/redis.conf

    worker:
        container_name: celery
        build: ./backend
        image: docker-server/backend
        env_file:
            - ./backend/.env.prod
        environment:
            - TZ=Asia/Seoul
        restart: always
        command: sh -c "celery -A config worker --loglevel=info & celery -A config beat --loglevel=info & wait"
        depends_on:
            - cache
