# Generated by Django 4.2.9 on 2024-01-16 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(help_text='이메일', max_length=30, unique=True)),
                ('password', models.CharField(help_text='비밀번호', max_length=20)),
                ('username', models.CharField(help_text='사용자 이름', max_length=20)),
                ('generation', models.IntegerField(help_text='기수')),
                ('role', models.CharField(choices=[('manager', '운영진'), ('member', '부원')], default='manager', help_text='역할', max_length=100)),
                ('workout_location', models.CharField(choices=[('일산', '일산'), ('연남', '연남'), ('양재', '양재'), ('신림', '신림')], help_text='운동 지점', max_length=100)),
                ('workout_level', models.CharField(choices=[('white', '하얀색'), ('yellow', '노란색'), ('orange', '주황색'), ('green', '초록색'), ('blue', '파란색'), ('red', '빨간색'), ('purple', '보라색'), ('grey', '회색'), ('brown', '갈색'), ('black', '검정색')], help_text='운동 난이도', max_length=100)),
                ('profile_number', models.IntegerField(help_text='프로필 번호')),
                ('introduction', models.TextField(help_text='소개글')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정 일시')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
