# Generated by Django 4.2.9 on 2024-08-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='generation',
            field=models.CharField(choices=[('1기', '1기'), ('2기', '2기'), ('3기', '3기'), ('4기', '4기'), ('5기', '5기'), ('6기', '6기'), ('7기', '7기'), ('8기', '8기'), ('9기', '9기'), ('10기', '10기'), ('11기', '11기'), ('12기', '12기')], help_text='기수', max_length=10),
        ),
    ]
