# Generated by Django 4.2.9 on 2024-03-05 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='이메일', max_length=254, unique=True)),
                ('code', models.IntegerField(help_text='인증 번호')),
                ('status', models.BooleanField(default=False, help_text='인증 상태')),
            ],
            options={
                'db_table': 'auth_status',
            },
        ),
    ]
