# Generated by Django 4.2.9 on 2024-04-24 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_delete_userregistrationemailauthstatus_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordUpdateEmailAuthStatus',
        ),
    ]
