# Generated by Django 4.2.9 on 2024-03-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_authstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='authstatus',
            name='created_at',
            field=models.DateTimeField(auto_now=True, help_text='생성 시간'),
        ),
    ]
