# Generated by Django 4.2.9 on 2024-03-15 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_authstatus_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuthStatus',
            new_name='UserRegistrationEmailAuthStatus',
        ),
        migrations.AlterModelTable(
            name='userregistrationemailauthstatus',
            table='user_register_auth_status',
        ),
    ]
