# Generated by Django 4.2.9 on 2024-03-16 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_authstatus_userregistrationemailauthstatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordUpdateEmailAuthStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='이메일', max_length=254, unique=True)),
                ('code', models.IntegerField(help_text='인증 번호')),
                ('created_at', models.DateTimeField(auto_now=True, help_text='생성 시간')),
            ],
            options={
                'db_table': 'password_update_email_auth_status',
            },
        ),
    ]
