# Generated by Django 4.2.9 on 2024-05-04 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.PositiveIntegerField(help_text='운동 기간')),
                ('week', models.PositiveIntegerField(help_text='운동 주차')),
                ('score', models.FloatField(default=0.0, help_text='운동 점수')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 시각')),
                ('user', models.ForeignKey(help_text='사용자 ID', on_delete=django.db.models.deletion.CASCADE, related_name='ranking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ranking',
                'ordering': ['week'],
            },
        ),
    ]
