# Generated by Django 4.2.9 on 2024-05-04 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnavailableDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_location', models.CharField(choices=[('더클라임 일산', '더클라임 일산'), ('더클라임 연남', '더클라임 연남'), ('더클라임 양재', '더클라임 양재'), ('더클라임 신림', '더클라임 신림')], help_text='운동 지점', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'unavailable_date',
            },
        ),
        migrations.CreateModel(
            name='AttendanceStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.IntegerField(default=0, help_text='출석 횟수')),
                ('late', models.IntegerField(default=0, help_text='지각 횟수')),
                ('absence', models.IntegerField(default=0, help_text='결석 횟수')),
                ('substitute', models.IntegerField(default=0, help_text='대체 출석 횟수')),
                ('attendance_rate', models.FloatField(help_text='출석률')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attendance_stats',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_location', models.CharField(choices=[('더클라임 일산', '더클라임 일산'), ('더클라임 연남', '더클라임 연남'), ('더클라임 양재', '더클라임 양재'), ('더클라임 신림', '더클라임 신림')], help_text='운동 지점', max_length=100, null=True)),
                ('week', models.IntegerField(help_text='주차', null=True)),
                ('request_time', models.DateTimeField(help_text='출석 요청 시간', null=True)),
                ('request_processed_status', models.CharField(choices=[('승인', '승인'), ('거절', '거절')], help_text='요청 상태', max_length=20, null=True)),
                ('request_processed_time', models.DateTimeField(help_text='요청 처리 시간', null=True)),
                ('attendance_status', models.CharField(choices=[('출석', '출석'), ('지각', '지각'), ('결석', '결석'), ('대체 출석', '대체 출석')], help_text='출석 상태', max_length=20, null=True)),
                ('request_processed_user', models.ForeignKey(help_text='요청을 처리한 사용자', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processed_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='사용자 ID', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attendance',
                'ordering': ['-request_time'],
            },
        ),
    ]
