# Generated by Django 4.2.9 on 2024-02-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(help_text='사용자 ID')),
                ('workout_location', models.CharField(choices=[('더클라임 일산', '더클라임 일산'), ('더클라임 연남', '더클라임 연남'), ('더클라임 양재', '더클라임 양재'), ('더클라임 신림', '더클라임 신림')], help_text='운동 지점', max_length=100)),
                ('week', models.IntegerField(help_text='주차')),
                ('request_time', models.DateTimeField(help_text='출석 요청 시간')),
                ('request_processed_status', models.CharField(choices=[('승인', '승인'), ('거절', '거절')], help_text='요청 상태', max_length=20)),
                ('request_processed_time', models.DateTimeField(help_text='요청 처리 시간')),
                ('request_processed_user_id', models.IntegerField(help_text='요청을 처리한 사용자 ID')),
                ('attendance_status', models.CharField(choices=[('출석', '출석'), ('지각', '지각'), ('결석', '결석'), ('대체 출석', '대체 출석')], help_text='출석 상태', max_length=20)),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
    ]
