# Generated by Django 4.2.9 on 2024-02-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_unavailabledate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance_status',
            field=models.CharField(choices=[('출석', '출석'), ('지각', '지각'), ('결석', '결석'), ('대체 출석', '대체 출석')], help_text='출석 상태', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='request_processed_status',
            field=models.CharField(choices=[('승인', '승인'), ('거절', '거절')], help_text='요청 상태', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='request_processed_time',
            field=models.DateTimeField(help_text='요청 처리 시간', null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='request_processed_user_id',
            field=models.IntegerField(help_text='요청을 처리한 사용자 ID', null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='week',
            field=models.IntegerField(help_text='주차', null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='workout_location',
            field=models.CharField(choices=[('더클라임 일산', '더클라임 일산'), ('더클라임 연남', '더클라임 연남'), ('더클라임 양재', '더클라임 양재'), ('더클라임 신림', '더클라임 신림')], help_text='운동 지점', max_length=100, null=True),
        ),
    ]
