# Generated by Django 4.2.9 on 2024-02-28 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_attendance_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='user_id',
            new_name='user',
        ),
    ]
