# Generated by Django 4.2.9 on 2024-02-28 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0006_rename_user_id_attendance_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='request_processed_user_id',
        ),
        migrations.AddField(
            model_name='attendance',
            name='request_processed_user',
            field=models.ForeignKey(help_text='요청을 처리한 사용자', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processed_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(help_text='사용자 ID', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL),
        ),
    ]
