# Generated by Django 4.2.9 on 2024-02-29 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_remove_attendance_request_processed_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='request_time',
            field=models.DateTimeField(help_text='출석 요청 시간', null=True),
        ),
    ]
