# Generated by Django 4.2.9 on 2024-02-29 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0008_alter_attendance_request_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.IntegerField(default=0, help_text='출석 횟수')),
                ('late', models.IntegerField(default=0, help_text='지각 횟수')),
                ('absence', models.IntegerField(default=0, help_text='결석 횟수')),
                ('substitute', models.IntegerField(default=0, help_text='대체 출석 횟수')),
                ('attendance_rate', models.FloatField(help_text='출석률')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attendance_stats',
            },
        ),
    ]
