# Generated by Django 4.2.9 on 2024-08-29 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_location', models.CharField(choices=[('더클라임 일산', '더클라임 일산'), ('더클라임 연남', '더클라임 연남'), ('더클라임 양재', '더클라임 양재'), ('더클라임 신림', '더클라임 신림'), ('더클라임 마곡', '더클라임 마곡'), ('더클라임 홍대', '더클라임 홍대'), ('더클라임 서울대', '더클라임 서울대'), ('더클라임 강남', '더클라임 강남'), ('더클라임 사당', '더클라임 사당'), ('더클라임 신사', '더클라임 신사'), ('더클라임 논현', '더클라임 논현'), ('더클라임 문래', '더클라임 문래')], max_length=100, verbose_name='지점')),
                ('start_time', models.DateTimeField(verbose_name='운동 시작 시간')),
                ('end_time', models.DateTimeField(verbose_name='운동 종료 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('generation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record', to='account.generation', verbose_name='운영 기수')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '기록',
                'verbose_name_plural': '기록',
                'db_table': 'record',
            },
        ),
        migrations.CreateModel(
            name='BoulderProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_level', models.IntegerField(choices=[(1, '하얀색'), (2, '노란색'), (3, '주황색'), (4, '초록색'), (5, '파란색'), (6, '빨간색'), (7, '보라색'), (8, '회색'), (9, '갈색'), (10, '검정색')], verbose_name='난이도')),
                ('count', models.PositiveIntegerField(verbose_name='해결한 문제 개수')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boulder_problems', to='record.record', verbose_name='기록')),
            ],
            options={
                'verbose_name': '해결한 문제',
                'verbose_name_plural': '해결한 문제',
                'db_table': 'boulder_problem',
            },
        ),
    ]
