name: Continuous Deployment

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deployment
    runs-on: ubuntu-latest
    if: github.repository == 'ROCCIA-901/roccia_901_server'
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: create env file
      run: |
        touch .env.prod
        echo "${{ secrets.PROD_ENV }}" >> .env.prod

    - name: create remote directory
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: mkdir -p /home/ubuntu/srv

    - name: Copy source via ssh key excluding logs
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete --exclude='backend/logs/*' --exclude='nginx/logs/*'
        remote_path: /home/ubuntu/srv/
        remote_host: ${{ secrets.SSH_HOST }}
        remote_user: ${{ secrets.SSH_USERNAME }}
        remote_key: ${{ secrets.SSH_KEY }}

    - name: transfer env file
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: ".env.prod"
        target: "/home/ubuntu/srv/backend/"

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        working-directory: /home/ubuntu/srv
        script: |
          sh /home/ubuntu/srv/deploy.sh
